### ISSUE TITLE
Broken link for Docker Airflow Spark example

### ISSUE THREAD

**Issue by jalessandro** [nanlabs/awesome-nan#10]
### Describe the issue

In the README file there is a broken link: https://github.com/nanlabs/devops-reference/tree/main/examples/compose-airflow/
I believe that the correct one is: https://github.com/nanlabs/devops-reference/tree/main/examples/compose-airflow-spark

### Links

https://github.com/nanlabs/awesome-nan/blob/main/README.md

**Comment by ulises-jeremias** [comment]
@jalessandro thanks for opening the issue! I fixed it on both, awesome-nan and devops-reference!

https://github.com/nanlabs/devops-reference/commit/e51fb8b48ad4e6e07d55f1605f896994f5046ebf
